---
- hosts: localhost
  name: Provision OCP Cluster
  connection: local
  gather_facts: false

  pre_tasks:
    - name: Convert host_csv to Array
      set_fact:
        shortnames: "{{ host_csv.split(',') }}"
        hostnames: []

    - debug:
        var: shortnames
        verbosity: 2

    - name: Convert shortnames to hostnames
      set_fact:
        hostnames: "{{ hostnames }} + ['{{ item }}.{{ host_dns_id }}.{{ host_dns_suffix }}']"
      with_items:
        - "{{ shortnames }}"

    - debug:
        var: hostnames
        verbosity: 2

    - name: Get Host Array Length
      set_fact:
        number_vms: "{{ hostnames | length }}"

    - debug:
        var: number_vms
        verbosity: 2

    - name: Fail if number_vms > 10
      fail:
        msg: "Number of VMs too large: {{ number_vms }}"
      when: number_vms | int > 10

  roles:
    - role: phpipam
    - role: ocp_inventory
    - role: idm
    - role: rhv
    - { role: manageiq, when: manageiq is defined }

- hosts: OSEv3
  name: Deploy OpenShift v3.7 Using BYO

  roles:
    - { role: ocp_prep_nodes, when: ocp_call_byo_playbooks is defined }
#    - { role: ocp_call_byo, when: ocp_call_byo_playbooks is defined }

- import_playbook: /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml
