---
- name: Provision VM
  hosts: localhost
  connection: local
  gather_facts: false

  roles:
    - { role: phpipam, when: ip_address is not defined }
    - role: idm
    - role: rhv
    - { role: manageiq, when: manageiq is defined }
