---
- hosts: localhost
  name: Provision VM(s)
  connection: local
  gather_facts: false

  pre_tasks:
    - name: Convert host_csv to Array
      set_fact:
        hostnames: "{{ host_csv.split(',') }}"

    - debug: var=hostnames
      verbosity: 2

    - name: Get Host Array Length
      set_fact:
        number_vms: "{{ hostnames | length }}"

    - debug: var=number_vms
      verbosity: 2

    - name: Fail if number_vms > 10
      fail:
        msg: "Number of VMs too large: {{ number_vms }}"
      when: number_vms | int > 10

  roles:
    - role: phpipam
    - role: dynamic_hostgroup
    - role: idm
    - role: rhv
    - { role: manageiq, when: manageiq is defined }

# Example for use with dynamic_inventory (probably more suitable as another role)
- hosts: dynamic_inventory
  name: Configure VM(s)

  tasks:
    - name: Ensure SELinux is enabled/enforcing
      selinux:
        policy: targeted
        state: permissive
