- hosts: localhost
  connection: local
  tasks:

    - set_fact:
        ip_addresses: ['10.11.165.12','10.11.165.13']
        vm_names: ['admiyo1','admiyo2']
        vm_domain: demo.rdu.salab.redhat.com

    - name: Source Vault
      include_vars: vault.yml


    - debug: var=vm_names


    - name: Generate phpipam Token
      uri:
        url: "http://{{ php_ipam_hostname }}/api/{{ php_ipam_api_user }}/user/"
        method: POST
        user: "{{ php_ipam_username }}"
        password: "{{ php_ipam_password }}"
        force_basic_auth: true
        status_code: 200
      register: session

    - name: Delete IPs
      uri:
        url: "http://{{ php_ipam_hostname }}/api/demolab/addresses/{{ item }}/{{ php_ipam_subnet_id }}/"
        method: DELETE
        headers:
          phpipam-token: "{{ session.json.data.token }}"
        status_code: 200
      register: get_ip
      with_items:  "{{ ip_addresses }}"

  
    # Using API Because ipa_host module does not support update DNS
    # Also we don't have zone info for ipa_dnsrecord

    - name: Generate IPA Session Cookie
      uri:
        url: "https://{{ ipa_hostname }}/ipa/session/login_password"
        validate_certs: no
        method: POST
        status_code: 200
        headers:
          Content-Type: "application/x-www-form-urlencoded"
          Accept: "text/plain"
          Referer: "https://{{ ipa_hostname }}/ipa"
        body: "user={{ ipa_username }}&password={{ ipa_password }}"
      register: session


    - debug: var=session
      when: debug is defined

    - name: Remove Host from IPA & Update DNS
      uri:
        url: "https://{{ ipa_hostname }}/ipa/session/json"
        validate_certs: no
        method: POST
        status_code: 200
        headers:
          Cookie: "{{ session.set_cookie }}"
          Accept: "application/json"
          Referer: "https://{{ ipa_hostname }}/ipa"
        body:
          method: host_del
          params:
          - - "{{ item }}.{{vm_domain}}"
          - updatedns: true
        body_format: json
      register: host_del
      with_items:  "{{ vm_names }}"

    - debug: var=host_del
      when: debug is defined


    - name: Remove Host from RHV
      ovirt_vms:
        auth:
          username: "{{ rhv_username }}"
          password: "{{ rhv_password }}"
          url: "https://{{ rhv_hostname }}/ovirt-engine/api"
          insecure: true
        state: absent
        name: "{{ item }}.{{vm_domain}}"
        cluster: Default
      with_items:  "{{ vm_names }}"

      register: vms

    - debug: var=vms
      when: debug is defined
