---
rhv_template: "CLOUDSA-template-rhel74"
rhv_cluster: "RHHI-Hypervisors"
my_custom_script: |
  output: {all: '| tee -a /var/log/cloud-init-output.log'}
  runcmd:
   - /usr/bin/echo "DEVICE=eth0" > /etc/sysconfig/network-scripts/ifcfg-eth0
   - /usr/bin/echo "BOOTPROTO=none" >> /etc/sysconfig/network-scripts/ifcfg-eth0
   - /usr/bin/echo "IPADDR={{ ip_address }}" >> /etc/sysconfig/network-scripts/ifcfg-eth0
   - /usr/bin/echo "NETMASK=255.255.254.0" >> /etc/sysconfig/network-scripts/ifcfg-eth0
   - /usr/bin/echo "GATEWAY=10.11.165.254" >> /etc/sysconfig/network-scripts/ifcfg-eth0
   - /usr/bin/echo "DNS1=10.11.165.151" >> /etc/sysconfig/network-scripts/ifcfg-eth0
   - /usr/bin/echo "SEARCH=demo.rdu.salab.redhat.com" >> /etc/sysconfig/network-scripts/ifcfg-eth0
   - /sbin/ifdown eth0
   - /sbin/ifup eth0
   - /usr/bin/hostnamectl set-hostname "{{ vm_name }}"
   - /usr/sbin/ipa-client-install -w "{{ ipa_otp }}" --mkhomedir -U
   - /usr/bin/firewall-offline-cmd --zone=public --add-service ssh
   - /usr/bin/systemctl restart firewalld.service
   - /usr/bin/systemctl enable sshd.service
   - /usr/bin/systemctl start sshd.service
   - /usr/bin/systemctl stop cloud-init.service
   - /usr/bin/systemctl disable cloud-init.service
