---
- name: Register with CDN
  redhat_subscription:
    username: "{{ rhsm_username }}"
    password: "{{ rhsm_password }}"
    state: present
    pool_ids: "{{ rhsm_pool_id }}"

- name: Clean Slate Repositories
  command: subscription-manager repos --disable='*'
  creates: /tmp/.ansible_ran_clean_repos

- name: Enable Repositories
  command: subscription-manager repos --enable rhel-7-server-rpms --enable rhel-7-server-extras-rpms
  creates: /tmp/.ansible_ran_enable_repos

- name: Get Ansible Tower Installer
  get_url:
    url: "http://releases.ansible.com/ansible-tower/setup-bundle/ansible-tower-setup-bundle-{{ tower_version }}.el7.tar.gz"
    dest: "/tmp/ansible-tower-setup-bundle-{{ tower_version }}.el7.tar.gz"

- name: Extract Ansible Tower Installer
  unarchive:
    src: "/tmp/ansible-tower-setup-bundle-{{ tower_version }}.el7.tar.gz"
    dest: /tmp
    remote_src: true
    owner: root

- name: Copy Tower Inventory File
  template:
    src: templates/tower_inventory.j2
    dest: "/tmp/ansible-tower-setup-bundle-{{ tower_version }}.el7/inventory"

- name: execute the tower installation
  command: /tmp/ansible-tower-setup-bundle-{{ tower_version }}.el7/setup.sh
  register: towerinstall
  until: towerinstall.rc == 0
  retries: 3
  delay: 15
  ignore_errors: yes
