---
- name: Service Template Lookup (Catalog Item Lookup)
  uri:
    url: "https://{{ cfme_hostname }}/api/{{ manageiq.service }}"
    validate_certs: false
    method: GET
    user: "{{ cfme_username }}"
    password: "{{ cfme_password }}"
    headers:
      #X-Auth-Token: "{{ manageiq.api_token }}"
      Content-Type: "application/json"
    status_code: 200
  register: service

- debug: var=service
  when: debug is defined

- name: Query Tags from Service Template
  uri:
    url: "https://{{ cfme_hostname }}/api/service_templates/{{ service.json.service_template_id }}/tags"
    validate_certs: false
    method: GET
    user: "{{ cfme_username }}"
    password: "{{ cfme_password }}"
    headers:
      #X-Auth-Token: "{{ manageiq.api_token }}"
      Content-Type: "application/json"
    status_code: 200
  register: service_template_tags

- debug: var=service_template_tags.json.subcount
  when: debug is defined

- debug: var=service_template_tags.json.resources
  when: debug is defined

- name: Assign Tags to Service
  uri:
    url: "https://{{ cfme_hostname }}/api/{{ manageiq.service }}/tags"
    validate_certs: false
    method: POST
    user: "{{ cfme_username }}"
    password: "{{ cfme_password }}"
    headers:
      #X-Auth-Token: "{{ manageiq.api_token }}"
      Content-Type: "application/json"
    status_code: 200
    body:
      action: assign
      resources: "{{ service_template_tags.json.resources }}"
    body_format: json
  register: service_assign

- debug: var=service_assign
  when: debug is defined

- name: Add Tags to VM
  uri:
    url: "https://{{ cfme_hostname }}/api/vms/{{ uri_lookup_vm.json.resources[0].id }}/tags"
    validate_certs: false
    method: POST
    user: "{{ cfme_username }}"
    password: "{{ cfme_password }}"
    headers:
      #X-Auth-Token: "{{ manageiq.api_token }}"
      Content-Type: "application/json"
    status_code: 200
    body:
      action: assign
      resources: "{{ service_template_tags.json.resources }}"
    body_format: json
  register: uri_assign_tag

- debug: var=uri_assign_tag
  when: debug is defined
