---
- set_fact:
    today: "{{ lookup('pipe','date +%Y-%m-%d-%H-%M') }}"

- debug: var=today
  when: debug is defined

- name: Update Service Name
  uri:
    url: "https://{{ cfme_hostname }}/api/{{ manageiq.service }}"
    validate_certs: false
    method: PUT
    user: "{{ cfme_username }}"
    password: "{{ cfme_password }}"
    headers:
      #X-Auth-Token: "{{ manageiq.api_token }}"
      Content-Type: "application/json"
    status_code: 200
    body:
      name: "{{ vm_name }} - Created on {{ today }}"
    body_format: json
  register: uri_update_name

- debug: var=uri_update_name
  when: debug is defined
