---
- name: Lookup CloudForms VM via uid_ems
  uri:
    url: "https://{{ cfme_hostname }}/api/vms?filter[]=uid_ems={{ vm.id }}&expand=resources"
    validate_certs: false
    method: GET
    user: "{{ cfme_username }}"
    password: "{{ cfme_password }}"
    headers:
      #X-Auth-Token: "{{ manageiq.api_token }}"
      Content-Type: "application/json"
    status_code: 200
    body:
      action: refresh
    body_format: json
  register: uri_lookup_vm
  until: uri_lookup_vm.json.subcount > 0
  retries: 10
  delay: 10

- debug: var=uri_lookup_vm
  when: debug is defined

- debug: var=uri_lookup_vm.json.resources[0].id
  when: debug is defined

- name: Add VM to Service
  uri:
    url: "https://{{ cfme_hostname }}/api/{{ manageiq.service }}"
    validate_certs: false
    method: POST
    user: "{{ cfme_username }}"
    password: "{{ cfme_password }}"
    headers:
      #X-Auth-Token: "{{ manageiq.api_token }}"
      Content-Type: "application/json"
    status_code: 200
    body:
      action: add_resource
      resource: "{ \"resource\": { \"href\": \"/api/vms/{{ uri_lookup_vm.json.resources[0].id }}\" } }"
    body_format: json
  register: uri_add_vm

- debug: var=uri_add_vm
  when: debug is defined
